[phases.setup]
nixPkgs = ["python310", "unzip"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
    "chmod +x download_models_railway_v2.sh",
    ". /opt/venv/bin/activate && bash download_models_railway_v2.sh"
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn -k uvicorn.workers.UvicornWorker -w 1 -b 0.0.0.0:$PORT app:app"
