[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "chmod +x download_models_railway.sh",
  "./download_models_railway.sh"
]

[start]
cmd = "gunicorn -k uvicorn.workers.UvicornWorker -w 1 -b 0.0.0.0:$PORT app:app"
